[project]
name = "watermark-competition"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ldpc>=2.4.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
    "pip>=26.0.1",
    "scikit-image>=0.26.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
