project:
  type: website
  title: "Multimedia Security and Privacy"
  output-dir: ../_site

website:
  navbar:
    search: true
    right:
      - text: Language
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: ../fr/index.html

  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - section: "Course"
        contents:
          - section: "Chapter 1: Introduction"
            contents:
              - section: "Details"
                href: ch1c.qmd
              - ch1.qmd
              - section: "Synthesis"
                href: ch1r.qmd
          - section: "Chapter 2: Notations & Core Concepts"
            contents:
              - section: "Details"
                href: ch2c.qmd
              - ch2.qmd
              - section: "Synthesis"
                href: ch2r.qmd
          - section: "Chapter 3: Digital Watermarking"
            contents:
              - section: "Details"
                href: ch3c.qmd
              - ch3.qmd
              - section: "Synthesis"
                href: ch3r.qmd
          - section: "Chapter 4: Privacy-Preserving Methods"
            contents:
              - section: "Details"
                href: ch4c.qmd
              - ch4.qmd
              - section: "Synthesis"
                href: ch4r.qmd

format:
  html:
    theme:
      light: ../latte.scss
      dark: ../macchiato.scss
    toc: true
    embed-resources: true

filters:
  - diagram
