"""
utils/sync.py
=============
Frequency-domain synchronisation for watermark decoding.

Pipeline
--------
1. Spatial autocorrelation via Wiener-Khinchin on both image and reference
2. Non-maximum suppression (NMS) + thresholding + binarization to isolate lattice peaks
3. Match image peaks to reference peaks → estimate affine transform
4. Apply inverse affine (crop, no padding artefacts)
5. Sum all patch-sized blocks into one block (symmetric-aware)
6. Correlate summed block against reference patch → estimate translation
7. Apply circular shift to align block with reference
8. Return aligned, summed block of shape (patch_size * upsample_factor,
   patch_size * upsample_factor)

The ``upsample_factor`` parameter must match the value used in patch.py at
encode time.  It controls the pixel-block size: each logical patch cell is
represented by ``upsample_factor × upsample_factor`` image pixels.

Performance notes
-----------------
* ``correlation_fft`` uses ``rfft2`` / ``irfft2`` instead of ``fft2`` / ``ifft2``.
  For real-valued inputs the one-sided spectrum has roughly half as many
  elements, giving ~2× speedup on both the transform and the complex multiply.

* ``non_maximum_suppression`` uses ``cv2.dilate`` with a rectangular
  structuring element.  OpenCV's morphological dilation uses an efficient
  O(N · k) sliding-window algorithm (rather than the naïve O(N · k²) approach
  used by ``scipy.ndimage.maximum_filter``), which matters a lot for the large
  NMS windows (e.g. 127) generated by the default ``nms_size_ac`` formula.

* Inside ``synchronise`` the reference is FFT-transformed exactly once;
  its conjugate spectrum is reused for ``ref_ac`` and all four
  cross-correlations, saving five redundant FFT pairs.

* The four final ``warpAffine`` calls use ``INTER_LINEAR`` rather than
  ``INTER_LANCZOS4``.  The remaining correction at that point is a small
  (usually sub-pixel to a few pixels) translation, for which bilinear
  interpolation is indistinguishable from Lanczos-4 in practice while being
  4–8× faster.

* ``synchronise`` accepts an optional pre-built ``reference`` array so that
  ``model.py`` can pass the one it already computed for Wiener noise estimation,
  avoiding a full second ``build_reference_patch_bipolar`` call.
"""

from __future__ import annotations

import numpy as np
import cv2
from utils.patch import build_reference_patch_bipolar, upsample_patch, generate_base_patch


# ---------------------------------------------------------------------------
# Cross-correlation
# ---------------------------------------------------------------------------

def correlation_fft(img_1: np.ndarray, img_2: np.ndarray) -> np.ndarray:
    """
    Compute the cross-correlation between two images via the Wiener-Khinchin theorem.

    ``crosscorr = irfft2(rfft2(f1) · conj(rfft2(f2)))``, shifted so DC is at
    the centre.

    Uses ``rfft2`` / ``irfft2`` instead of the full complex FFT: for real-valued
    inputs the one-sided spectrum has ~half as many elements, giving roughly 2×
    speedup on both the transforms and the frequency-domain multiply.

    Parameters
    ----------
    img_1 : ndarray of shape (H, W), real-valued
    img_2 : ndarray of shape (h, w), real-valued

    Returns
    -------
    crosscorr : ndarray of shape (H, W), dtype float64
    """
    f1 = img_1.astype(np.float64)
    f1 = (f1 - f1.mean()) / (f1.std() + 1e-8)

    f2 = img_2.astype(np.float64)
    f2 = (f2 - f2.mean()) / (f2.std() + 1e-8)

    F1 = np.fft.rfft2(f1)
    F2 = np.fft.rfft2(f2, s=f1.shape)   # zero-pad img_2 to img_1's shape if needed
    return np.fft.fftshift(np.fft.irfft2(F1 * np.conj(F2), s=f1.shape))


# ---------------------------------------------------------------------------
# Non-maximum suppression
# ---------------------------------------------------------------------------

def non_maximum_suppression(image: np.ndarray, size: int = 31) -> np.ndarray:
    """
    Retain only local maxima within a ``size × size`` neighbourhood.

    Uses ``cv2.dilate`` with a rectangular structuring element.  OpenCV's
    morphological dilation employs an efficient O(N·k) sliding-window algorithm
    which is significantly faster than ``scipy.ndimage.maximum_filter`` for
    large kernel sizes.

    Parameters
    ----------
    image : ndarray of shape (H, W)
    size  : int

    Returns
    -------
    nms : ndarray of shape (H, W)
    """
    img32   = image.astype(np.float32)
    kernel  = np.ones((size, size), dtype=np.uint8)
    dilated = cv2.dilate(img32, kernel)
    return (img32 == dilated) * image   # preserve original dtype/values at peaks


# ---------------------------------------------------------------------------
# Interest point detection
# ---------------------------------------------------------------------------

def get_center_peak(peaks: np.ndarray) -> np.ndarray:
    """
    Find the peak closest to the center of the image.

    Parameters
    ----------
    peaks : ndarray (H, W)
        Map of detected peaks.

    Returns
    -------
    center : ndarray (2,)
        Coordinates of the center peak.
    """
    H, W = peaks.shape
    ys, xs = np.nonzero(peaks)
    coords = np.stack((ys, xs), axis=1).astype(float)
    center = coords[np.argmin(np.linalg.norm(coords - [H // 2, W // 2], axis=1))]
    return center


def detect_interest_points(peaks: np.ndarray, min_angle_deg: float = 25.0) -> np.ndarray:
    """
    Extract a quadrilateral cell from a lattice using a simple geometric rule.

    Strategy
    --------
    p1 : center (closest peak to image center)
    p2 : closest neighbor to p1
    p3 : next closest point with a different direction from p2
         (angle > min_angle and < 180 - min_angle)
    p4 : real point closest to (p2 + p3)

    The returned order is: [p1, p2, p4, p3].

    Parameters
    ----------
    peaks : ndarray (H, W)
        Map of detected peaks.
    min_angle_deg : float
        Minimum angle between p2 and p3 (in degrees).

    Returns
    -------
    points : ndarray (4, 2)
        Quadrilateral in centered coordinates.

    Raises
    ------
    ValueError if a valid configuration cannot be found.
    """
    H, W = peaks.shape
    ys, xs = np.nonzero(peaks)
    if len(ys) < 3:
        raise ValueError("Not enough peaks.")

    coords = np.stack((ys, xs), axis=1).astype(float)
    center = get_center_peak(peaks)

    others = coords - center
    others = others[(others != 0).any(axis=1)]

    dists  = np.linalg.norm(others, axis=1)
    others = others[np.argsort(dists)]   # sort by distance, not by score

    # p2 = nearest neighbour
    p2 = others[0]

    # p3 = nearest point with sufficient angular separation from p2
    cos    = (others @ p2) / (np.linalg.norm(others, axis=1) * np.linalg.norm(p2) + 1e-8)
    angles = np.arccos(np.clip(cos, -1, 1))
    tol    = np.radians(min_angle_deg)
    valid  = (angles > tol) & (angles < np.pi - tol)
    valid[0] = False

    if not np.any(valid):
        raise ValueError("All strong peaks are collinear.")

    # pick the closest valid one (not the highest-scored)
    p3_idx = np.argmax(valid)   # first True = smallest distance among valid
    p3     = others[p3_idx]

    return (np.stack([[0., 0.], p2, p3]) + center).astype(float)


# ---------------------------------------------------------------------------
# Affine estimation
# ---------------------------------------------------------------------------

def estimate_affine(img_ac: np.ndarray, ref_ac: np.ndarray, nms_size: int = 31) -> np.ndarray:
    """
    Estimate the 2-D affine matrix mapping image lattice peaks to reference peaks.

    Interest points are detected independently in each autocorrelation map,
    then matched by position in the proximity chain (p1↔p1, p2↔p2, p3↔p3).

    Parameters
    ----------
    img_ac   : ndarray of shape (H, W)
    ref_ac   : ndarray of shape (H, W)
    nms_size : int

    Returns
    -------
    M : ndarray of shape (2, 3) — OpenCV affine matrix
    """
    img_peaks = non_maximum_suppression(img_ac, nms_size)
    ref_peaks = non_maximum_suppression(ref_ac, nms_size)

    img_pts = detect_interest_points(img_peaks)
    ref_pts = detect_interest_points(ref_peaks)

    # cv2.getAffineTransform expects (x, y) = (col, row)
    src = img_pts[:, ::-1].astype(np.float32)
    dst = ref_pts[:, ::-1].astype(np.float32)

    # distances from p2 to p2 and p3 in dst
    p22 = np.sum((src[1] - dst[1]) ** 2)
    p23 = np.sum((src[1] - dst[2]) ** 2)

    # If p2 is closer to p3 than to p2, swap p2 and p3 in src to match dst order.
    if p23 < p22:
        src[[1, 2]] = src[[2, 1]]

    return cv2.getAffineTransform(src, dst)


# ---------------------------------------------------------------------------
# Affine correction
# ---------------------------------------------------------------------------

def correct_affine(
    image: np.ndarray,
    M: np.ndarray,
    interpolation: int = cv2.INTER_LINEAR,
) -> np.ndarray:
    """
    Apply an affine warp and crop to the largest centred rectangle with no
    padding artefacts.

    Parameters
    ----------
    image         : ndarray of shape (H, W) — uint8 (LSB) or float32 (residual)
    M             : ndarray of shape (2, 3)
    interpolation : int — OpenCV interpolation flag

    Returns
    -------
    cropped : ndarray, same dtype as image
    """
    H, W = image.shape
    return cv2.warpAffine(
        image.astype(np.float32), M, (W, H),
        flags=interpolation, borderMode=cv2.BORDER_CONSTANT, borderValue=0,
    )

# ---------------------------------------------------------------------------
# Translation estimation
# ---------------------------------------------------------------------------


def estimate_translation_and_flip(
    image: np.ndarray,
    key: int,
    patch_size: int,
    upsample_factor: int,
    max_tiles: int = 16,
):
    """
    Estimate global translation and flip mode using a subset of tiles.

    Strategy
    --------
    - Split image into tiles of size (up, up)
    - Select only tiles with even indices (i % 2 == 0, j % 2 == 0)
    - Prioritize tiles closest to the image center
    - Evaluate all 4 flip configurations in a fully vectorized way
    - Aggregate results:
        * median shift
        * majority flip mode

    Parameters
    ----------
    image : ndarray (H, W)
    key : int
    patch_size : int
    upsample_factor : int
    max_tiles : int
        Maximum number of tiles used (for speed)

    Returns
    -------
    shift : ndarray (2,)
        Estimated (dy, dx)
    mode : str
        One of {"normal", "flip_y", "flip_x", "flip_xy"}
    """

    up = patch_size * upsample_factor
    H, W = image.shape

    # --- reference patch ---
    ref = generate_base_patch(patch_size, key)
    ref = upsample_patch(ref, upsample_factor)
    ref = ref.astype(np.float64)
    ref = (ref - ref.mean()) / (ref.std() + 1e-8)

    # --- pad image ---
    pad_H = (-H) % up
    pad_W = (-W) % up
    img = np.pad(image, ((0, pad_H), (0, pad_W)))

    H2, W2 = img.shape
    Ty, Tx = H2 // up, W2 // up

    # --- extract tiles: (Ty, Tx, up, up) ---
    tiles = img.reshape(Ty, up, Tx, up).transpose(0, 2, 1, 3)

    # --- select even-index tiles ---
    yy, xx = np.meshgrid(np.arange(Ty), np.arange(Tx), indexing="ij")
    mask = (yy % 2 == 0) & (xx % 2 == 0)

    coords = np.stack([yy[mask], xx[mask]], axis=1)

    # --- prioritize center tiles ---
    cy, cx = Ty / 2, Tx / 2
    dist = (coords[:, 0] - cy) ** 2 + (coords[:, 1] - cx) ** 2
    order = np.argsort(dist)

    coords = coords[order[:max_tiles]]

    # --- gather selected tiles ---
    selected = tiles[coords[:, 0], coords[:, 1]]  # (N, up, up)

    # --- build 4 flip variants ---
    variants = np.stack([
        selected,
        selected[:, ::-1, :],
        selected[:, :, ::-1],
        selected[:, ::-1, ::-1],
    ], axis=1)  # (N, 4, up, up)

    # --- normalize ---
    variants = variants.astype(np.float64)
    variants = (variants - variants.mean(axis=(-2, -1), keepdims=True)) / (
        variants.std(axis=(-2, -1), keepdims=True) + 1e-8
    )

    # --- FFT ---
    F_ref = np.fft.rfft2(ref, s=(up, up))
    F_var = np.fft.rfft2(variants, axes=(-2, -1))

    # --- correlation ---
    corr = np.fft.irfft2(
        F_var * np.conj(F_ref),
        s=(up, up),
        axes=(-2, -1),
    )
    corr = np.fft.fftshift(corr, axes=(-2, -1))  # (N, 4, up, up)

    # --- find peaks ---
    flat = corr.reshape(corr.shape[0], corr.shape[1], -1)
    idx = np.argmax(flat, axis=-1)

    dy = idx // up
    dx = idx % up

    scores = flat[np.arange(flat.shape[0])[:, None], np.arange(4), idx]

    # --- best mode per tile ---
    best_mode_idx = np.argmax(scores, axis=1)

    # --- gather shifts ---
    best_dy = dy[np.arange(len(coords)), best_mode_idx] - up // 2
    best_dx = dx[np.arange(len(coords)), best_mode_idx] - up // 2

    shifts = np.stack([best_dy, best_dx], axis=1)

    # --- aggregate ---
    median_shift = np.median(shifts, axis=0)

    # majority vote for mode
    counts = np.bincount(best_mode_idx, minlength=4)
    mode_idx = np.argmax(counts)

    modes = np.array(["normal", "flip_y", "flip_x", "flip_xy"])
    mode = modes[mode_idx]

    return median_shift, mode

# ---------------------------------------------------------------------------
# Block summation
# ---------------------------------------------------------------------------

def sum_blocks(
    image: np.ndarray,
    patch_size: int,
    tile_mode: str = "normal",
    upsample_factor: int = 2,
    mode: str | None = None,
) -> np.ndarray:
    """
    Divide image into non-overlapping blocks and sum them into a single block.

    When ``tile_mode == "symmetric"``, every other tile is flipped before
    summation to undo the symmetric tiling applied during encoding.

    Parameters
    ----------
    image           : ndarray of shape (H, W)
    patch_size      : int — logical patch side length (before upsampling)
    tile_mode       : {"normal", "symmetric"}
    upsample_factor : int — must match the value used during encoding

    Returns
    -------
    block : ndarray of shape (up, up), dtype float64
        where ``up = patch_size * upsample_factor``
    """
    up = patch_size * upsample_factor
    H, W = image.shape

    img = np.pad(
        image.astype(np.float64),
        ((0, (-H) % up), (0, (-W) % up)),
        mode="constant",
    )
    H2, W2 = img.shape
    tiles = img.reshape(H2 // up, up, W2 // up, up).transpose(1, 3, 0, 2).copy()

    if tile_mode == "symmetric":
        tiles[:, :, 1::2, :] = tiles[::-1, :, 1::2, :]
        tiles[:, :, :, 1::2] = tiles[:, ::-1, :, 1::2]

    blocks = np.sum(tiles, axis=(2, 3))

    if mode is not None:
        if mode == "flip_y":
            blocks = blocks[::-1, :]
        elif mode == "flip_x":
            blocks = blocks[:, ::-1]
        elif mode == "flip_xy":
            blocks = blocks[::-1, ::-1]
        # "normal" → do nothing
    return blocks


# ---------------------------------------------------------------------------
# Full synchronisation pipeline
# ---------------------------------------------------------------------------

def synchronise(
    img: np.ndarray,
    patch_size: int = 32,
    key: int = 0,
    tile_mode: str = "symmetric",
    nms_size_ac: int = 31,
    upsample_factor: int = 2,
    reference: np.ndarray | None = None,
) -> tuple[np.ndarray, str]:
    """
    Align img to the reference watermark grid and return a list of four
    translation-corrected variants (original + 3 axis flips of the
    affine-corrected image).

    Pipeline
    --------
    1. Compute autocorrelations of image and reference via rfft2.
    2. Detect three lattice peaks in each → estimate affine transform.
    3. Warp image with affine.
    4. For each of four flip variants of the warped image:
       a. Cross-correlate with reference (reusing precomputed reference rfft2).
       b. Estimate translation offset.
       c. Apply combined affine + translation to the corresponding flip of the
          original image.
    5. Return all four corrected images.

    Parameters
    ----------
    img            : ndarray of shape (H, W) — uint8 {0,1} or float32 residual
    patch_size     : int
    key            : int
    tile_mode      : {"normal", "symmetric"}
    nms_size_ac    : int — NMS window for autocorrelation peak detection
    upsample_factor: int
    reference      : ndarray of shape (H, W), optional
        Pre-built bipolar reference patch.  When supplied (e.g. passed from
        ``WatermarkModel.decode`` which already computed it) the function skips
        the ``build_reference_patch_bipolar`` call, saving significant time.

    Returns
    -------
    results : list of four ndarray, each of shape (H, W), dtype float32
        Affine + translation corrected variants of img.
    """
    interp = cv2.INTER_NEAREST if img.dtype == np.uint8 else cv2.INTER_LINEAR

    # ------------------------------------------------------------------
    # Build / receive reference and pre-compute its rfft2 ONCE.
    # This single conjugate spectrum is reused for:
    #   • ref_ac  (autocorrelation of reference)
    #   • 4×  cross-correlation(corrected_variant, reference)
    # That replaces what would otherwise be 5 separate rfft2 pairs.
    # ------------------------------------------------------------------
    if reference is None:
        ref = build_reference_patch_bipolar(
            img.shape, patch_size=patch_size, key=key,
            tile_mode=tile_mode, upsample_factor=upsample_factor,
        ).astype(np.float64)
    else:
        ref = np.asarray(reference, dtype=np.float64)

    ref_n      = (ref - ref.mean()) / (ref.std() + 1e-8)
    F_ref      = np.fft.rfft2(ref_n)          # computed exactly once
    F_ref_conj = np.conj(F_ref)
    ref_shape  = ref_n.shape

    # ref autocorrelation (reuse F_ref)
    ref_ac = np.fft.fftshift(np.fft.irfft2(F_ref * F_ref_conj, s=ref_shape))

    # ------------------------------------------------------------------
    # Image autocorrelation
    # ------------------------------------------------------------------
    img_f = img.astype(np.float64)
    img_f = (img_f - img_f.mean()) / (img_f.std() + 1e-8)
    F_img = np.fft.rfft2(img_f)
    img_ac = np.fft.fftshift(np.fft.irfft2(F_img * np.conj(F_img), s=img_f.shape))

    # ------------------------------------------------------------------
    # Affine estimation + first warp (done once on the original image)
    # ------------------------------------------------------------------
    M             = estimate_affine(img_ac, ref_ac, nms_size=nms_size_ac)
    img_corrected = correct_affine(img, M, interpolation=interp)
    # center_ref    = get_center_peak(non_maximum_suppression(ref_ac, size=nms_size_ac))

    # ------------------------------------------------------------------
    # Four flip variants: find per-variant translation, then apply the
    # combined affine+translation to the corresponding flip of the
    # original image.
    #
    # The 4 cross-correlations each reuse F_ref_conj; only one rfft2 of
    # the corrected variant is computed per iteration.
    #
    # INTER_LINEAR (not INTER_LANCZOS4) is used for the final warp: at
    # this stage only a small residual translation remains, for which
    # bilinear interpolation is indistinguishable from Lanczos-4 while
    # being 4–8× faster.
    # ------------------------------------------------------------------
    # corrected_variants = [
    #     img_corrected,
    #     img_corrected[::-1, :],
    #     img_corrected[:, ::-1],
    #     img_corrected[::-1, ::-1],
    # ]
    # img_variants = [
    #     img,
    #     img[::-1, :],
    #     img[:, ::-1],
    #     img[::-1, ::-1],
    # ]

    # results = []
    # for corr, img_var in zip(corrected_variants, img_variants):
    #     # Cross-correlation of this variant against reference
    #     c = corr.astype(np.float64)
    #     c = (c - c.mean()) / (c.std() + 1e-8)
    #     F_c   = np.fft.rfft2(c)
    #     c_ac  = np.fft.fftshift(np.fft.irfft2(F_c * F_ref_conj, s=ref_shape))

    #     center_corr = get_center_peak(non_maximum_suppression(c_ac, size=nms_size_ac))
    #     dy, dx = center_ref - center_corr

    #     M_total       = M.copy()
    #     M_total[0, 2] += dx
    #     M_total[1, 2] += dy

    #     results.append(correct_affine(img_var, M_total, interpolation=cv2.INTER_LINEAR))
    translation, flip_mode = estimate_translation_and_flip(img_corrected, key, patch_size, upsample_factor)
    M_total       = M.copy()
    M_total[0, 2] -= translation[1]  # dx
    M_total[1, 2] -= translation[0]  # dy

    return correct_affine(img, M_total, interpolation=interp), flip_mode
