project:
  type: website
  title: "Multimedia Security and Privacy"
  output-dir: ../_site/fr

website:
  # Language switching setup

  navbar:
    # background: primary
    search: true
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    
    contents:
      - index.qmd
      - section: "Cours"
        contents:
          - section: "Chapitre 1 — Introduction"
            contents:
              - ch1.qmd
              - section: "Détails"
                contents: ch1c.qmd
              - section: "Synthèse"
                contents: ch1r.qmd
          - section: "Chapitre 2 — Notations et Fondamentaux"
            contents:
              - ch2.qmd
              - section: "Détails"
                contents: ch2c.qmd
              - section: "Synthèse"
                contents: ch2r.qmd
          - section: "Chapitre 3 — Digital Watermarking"
            contents:
              - ch3.qmd
              - section: "Détails"
                contents: ch3c.qmd
              - section: "Synthèse"
                contents: ch3r.qmd
          - section: "Chapitre 4 — Protection de la Vie Privée"
            contents:
              - ch4.qmd
              - section: "Détails"
                contents: ch4c.qmd
              - section: "Synthèse"
                contents: ch4r.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    embed-resources: true
  # pdf:
  #   toc: true
  # docx:
  #   toc: true

filters:
  - diagram
