project:
  type: website
  title: "Sécurité et Confidentialité Multimédia"
  output-dir: ../_site/fr

website:
  navbar:
    search: true
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - section: "Cours"
        contents:
          - section: "Chapitre 1 : Introduction"
            contents:
              - section: "Détails"
                href: ch1c.qmd
              - ch1.qmd
              - section: "Synthèse"
                href: ch1r.qmd
          - section: "Chapitre 2 : Notations et Concepts"
            contents:
              - section: "Détails"
                href: ch2c.qmd
              - ch2.qmd
              - section: "Synthèse"
                href: ch2r.qmd
          - section: "Chapitre 3 : Digital Watermarking"
            contents:
              - section: "Détails"
                href: ch3c.qmd
              - ch3.qmd
              - section: "Synthèse"
                href: ch3r.qmd
          - section: "Chapitre 4 : Protection de la Vie Privée"
            contents:
              - section: "Détails"
                href: ch4c.qmd
              - ch4.qmd
              - section: "Synthèse"
                href: ch4r.qmd

format:
  html:
    theme:
      light: ../latte.scss
      dark: ../macchiato.scss
    toc: true
    embed-resources: true

filters:
  - diagram
